### ISSUE TITLE
字库错别字

### ISSUE THREAD

**Issue by ayssia** [fl0w1nd/sg0-ns-chs#1]
推的过程中看到有错别字

暧昧 → “暖”昧

（后面如果还看到有我会来补充）

**Comment by fl0w1nd** [comment]
> 推的过程中看到有错别字
> 
> 暧昧 → “暖”昧
> 
> （后面如果还看到有我会来补充）
感谢纠正，因为是OCR扫描制作的字库，很容易出现这种问题，我自己亲自把所有线通关了，但是难免会有漏网之鱼，我会在收集完错别字之后重新纠正字库

**Comment by ayssia** [comment]
另外目前双引号均显示为四个引号。

Edit: 主要是剧情对话里的。其它地方引号正常。

**Comment by fl0w1nd** [comment]
双引号问题暂时没有解决方案。因为NS原版英文版的人物对话就是用“ ”进行引用的，而PC版是用「 」引用人物对话的，正常情况下，但是对文本加载引擎而言它们都是相同的「 」作为人物对话标记语言。
